[supervisord]
nodaemon=true
logfile=/app/logs/supervisord.log
pidfile=/tmp/supervisord.pid
loglevel=info

[program:sync-worker]
command=php /app/src/worker.php
autostart=true
autorestart=true
stderr_logfile=/app/logs/worker.err.log
stdout_logfile=/app/logs/worker.out.log
startsecs=5
stopwaitsecs=10
